### ISSUE TITLE
Car Cap

### ISSUE THREAD

**Issue by MidnightYT1** [YoruDev-Ryland/WindowsGSM.BeamMP#1]
So ive put my vehicle cap to 10 in the server.cfg and its not actually setting the vehicle cap and the vehicle cap is only at 1 how can i change it from one to 10

**Comment by YoruDev-Ryland** [comment]
> So ive put my vehicle cap to 10 in the server.cfg and its not actually setting the vehicle cap and the vehicle cap is only at 1 how can i change it from one to 10

Hey I'm not at my computer right now but from memory, that was an option that I passed to the max player count inside of GSM.

Click on your beammp server in GSM, then in the bottom-left section, you will have an edit config button. Set your player number there and it should apply to the cars.
